version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Installing 
      - npm install
  pre_build:
    commands:     
      - npm run test
  build:
    commands:     
     - npm run build
     - aws s3 sync build s3://$SITE_BUCKET_NAME
