version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Installing 
      - npm install
  pre_build:
    commands:     
      - npm run test
  build:
    commands:     
     - npm run build
