version: 0.2
env:
  variables:
    SERVICE_NAME:             "python-serverless-template"
  parameter-store:
    SAM_S3_BUCKET:            "/python-serverless-template/build/SAM_S3_BUCKET"
    GITHUB_OWNER:             "/python-serverless-template/build/GITHUB_OWNER"
    GITHUB_REPO:              "/python-serverless-template/build/GITHUB_REPO"
    GITHUB_TOKEN:             "/python-serverless-template/build/GITHUB_TOKEN"

    PROD_ACCOUNT_ID:          "/python-serverless-template/build/PROD_ACCOUNT_ID"
    PROD_BUILD_REGIONS:       "/python-serverless-template/build/PROD_BUILD_REGIONS"

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      # Installing 
      - npm install
  pre_build:
    commands:     
      - npm run test
  build:
    commands:     
     - npm run build
