version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      # Installing 
      - npm install
      - echo "Staging Bucket Name $SITE_BUCKET_NAME"
  pre_build:
    commands:     
      - npm run test:unit
  build:
    commands:     
     - npm run build
